#!/usr/bin/env python

import os
import subprocess
import sys


def is_frobbable():
    # Get the root workspace
    workspace = subprocess.check_output("bazel info workspace".split()).strip()
    # Check the `WORKSPACE` file for our token.
    search_token = "drake_clion_environment"
    workspace_file = os.path.join(workspace, 'WORKSPACE')
    if os.path.exists(workspace_file):
        with open(workspace_file, 'r') as f:
            text = f.read()
            if search_token in text:
                return True
    return False


if __name__ == "__main__":
    # Copy args for modification.
    args = sys.argv[1:]

    # If this magic argument is found, replace it with our hooks instead.
    print("Frob check")
    if is_frobbable():
        print("Frobbing")
        old_magic = "--aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect"  # noqa
        new_magic = "--aspects=@drake//tools/clion:aspect.bzl%intellij_info_aspect"
        if old_magic in args:
            args[args.index(old_magic)] = new_magic

    # Delegate to bazel.
    os.execvp("bazel", ["bazel"] + args)
