load("//tools:drake.bzl", "drake_cc_googletest", "drake_cc_library")

drake_cc_googletest(
    name = "optional_port_test",
    srcs = ["optional_port_test.cc"],
    deps = [
        "//drake/systems/framework",
    ],
)
