# Can't name it `bazel_external_data` due to Python package clashes.
# @ref https://github.com/bazelbuild/bazel/issues/3998
workspace(name = "bazel_external_data_pkg")

load("//tools:path.bzl", "dirname")

# Include these as local repositories to have them be ignored by `test ...`.
# @ref https://github.com/bazelbuild/bazel/issues/2460#issuecomment-296940882
local_repository(
    name = "bazel_external_data_test_ignore",
    path = "test/workspaces",
)

# Need access to files in `//tools/lint/...`.
local_repository(
    name = "drake",
    path = dirname(__workspace_dir__, 3),
)

load("@drake//tools/workspace:github.bzl", "github_archive")

# Should only need a few externals for linting:
github_archive(
    name = "pycodestyle",
    repository = "PyCQA/pycodestyle",
    commit = "2.3.1",
    sha256 = "e9fc1ca3fd85648f45c0d2e33591b608a17d8b9b78e22c5f898e831351bacb03",  # noqa
    build_file = "externals/drake/tools/workspace/pycodestyle/pycodestyle.BUILD.bazel",
)

load("@drake//tools/workspace/buildifier:buildifier.bzl", "buildifier_repository")

buildifier_repository(
    name = "buildifier",
)
