#!/usr/bin/env python

import os
import sys

assert __name__ == "__main__"

# Check virtualenv
if not "VIRTUAL_ENV" in os.environ:
    raise Exception("Please ensure you use an `virtualenv`")

bin = "bazel-real"
argv = [bin] + sys.argv[1:]

# Delegate to bazel.
os.execvp(bin, argv)
